### PR TITLE
Feat/header nav

### PR DESCRIPTION
**Pull request by SICelineChan**
Created navbar

### CODE REVIEW

**Review by Codemon72 — DISMISSED** [review]
🦋👍

**Comment by SICelineChan** [comment]
I added some silly responsiveness to the nav bar. Please have a lookie!

**Review by Codemon72 — CHANGES_REQUESTED** [review]
I love the 🍔, but in md (768 - 1023px view screen) both burger and menu are visible.

**Comment by SICelineChan** [comment]
Yep, I can have a look at the responsiveness, probably on Friday

**Pull request merged**
